#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_contact:
    path: /contact
    controller: App\Controller\ContactController::index
app_form:
    path: /addtask
    controller: App\Controller\TaskController::new
app_add_product:
    path: /addProduct
    controller: App\Controller\ProductController::addProduct
app_home:
    path: /home
    controller: App\Controller\MainController::index
logout:
    path: /logout