#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app_add_product:
    path: /addProduct
    controller: App\Controller\ProductController::addProduct
app_home:
    path: /home
    controller: App\Controller\MainController::index
logout:
    path: /logout