#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_contact:
    path: /contact
    controller: App\Controller\ContactController::index
app_form:
    path: /addtask
    controller: App\Controller\TaskController::new